name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Test Information
        run: |
          echo "Event Trigger: ${{ github.event_name }}"
          echo "OS Type: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          path: repo
      - name: Create the zip archive
        uses: ./repo/.github/actions/zip
        with:
          working-directory: ${{ github.workspace }}/repo/my_lambda/src
          archive-file: ${{ runner.temp }}/lambda.zip
