name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      REPO_DIR: repo
    steps:
      - name: Test Information
        run: |
          echo "Event Trigger: ${{ github.event_name }}"
          echo "OS Type: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          path: ${{ env.REPO_DIR }}
      - name: Debug local action path
        run: |
          echo "github.workspace=${{ github.workspace }}"
          echo "repo.dir=${{ env.REPO_DIR }}"
          ls -la ${{ github.workspace }}
          ls -la ${{ github.workspace }}/${{ env.REPO_DIR }}
          ls -la ${{ github.workspace }}/${{ env.REPO_DIR }}/.github/actions
          ls -la ${{ github.workspace }}/${{ env.REPO_DIR }}/.github/actions/zip
      - name: Create the zip archive
        uses: ./repo/.github/actions/zip
        with:
          working-directory: ${{ github.workspace }}/${{ env.REPO_DIR }}/my_lambda/src
          archive-file: ${{ runner.temp }}/lambda.zip
